import {
  Controller,
  ForbiddenException,
  Get,
  Param,
  Query,
  Res,
} from "@nestjs/common";
import { Response } from "express";
import { HasuraAction } from "../hasura/hasura.controller";
import { User } from "../auth/types/User";
import { ScrimsService } from "./scrims.service";

@Controller("scrims")
export class ScrimsController {
  constructor(private readonly scrims: ScrimsService) {}

  // Public calendar-subscription feed. Calendar apps can't send auth headers,
  // so access is gated by a per-team unguessable token (HMAC of the team id)
  // rather than left open to teamId enumeration.
  @Get("calendar/:teamId.ics")
  async calendar(
    @Param("teamId") teamId: string,
    @Query("token") token: string,
    @Res() res: Response,
  ) {
    if (!this.scrims.validateCalendarToken(teamId, token)) {
      throw new ForbiddenException();
    }
    const ics = await this.scrims.getScrimCalendar(teamId);
    res.set("Content-Type", "text/calendar; charset=utf-8");
    res.set("Content-Disposition", `inline; filename="scrims-${teamId}.ics"`);
    res.send(ics);
  }

  @HasuraAction()
  public async scrimCalendarUrl(data: { user: User; team_id: string }) {
    const { user, team_id } = data;

    if (!(await this.scrims.isManager(team_id, user.steam_id))) {
      throw Error("you are not a manager of this team");
    }

    return {
      url: this.scrims.calendarUrl(team_id),
    };
  }

  @HasuraAction()
  public async sendScrimRequest(data: {
    user: User;
    from_team_id: string;
    to_team_id: string;
    proposed_scheduled_at: string;
    region?: string;
    best_of?: number;
  }) {
    const {
      user,
      from_team_id,
      to_team_id,
      proposed_scheduled_at,
      region,
      best_of,
    } = data;

    if (!(await this.scrims.isManager(from_team_id, user.steam_id))) {
      throw Error("you are not a manager of this team");
    }

    await this.scrims.createScrimRequest({
      fromTeamId: from_team_id,
      toTeamId: to_team_id,
      requestedBySteamId: user.steam_id,
      proposedScheduledAt: new Date(proposed_scheduled_at),
      region,
      bestOf: best_of,
      autoGenerated: false,
    });

    return {
      success: true,
    };
  }

  @HasuraAction()
  public async respondToScrimRequest(data: {
    user: User;
    request_id: string;
    accept: boolean;
  }) {
    const { user, request_id, accept } = data;

    await this.scrims.respondToScrimRequest({
      requestId: request_id,
      steamId: user.steam_id,
      accept,
    });

    return {
      success: true,
    };
  }

  @HasuraAction()
  public async counterScrimRequest(data: {
    user: User;
    request_id: string;
    proposed_scheduled_at: string;
  }) {
    const { user, request_id, proposed_scheduled_at } = data;

    await this.scrims.counterScrimRequest({
      requestId: request_id,
      steamId: user.steam_id,
      proposedScheduledAt: new Date(proposed_scheduled_at),
    });

    return {
      success: true,
    };
  }

  @HasuraAction()
  public async cancelScrimRequest(data: { user: User; request_id: string }) {
    const { user, request_id } = data;

    await this.scrims.cancelScrimRequest({
      requestId: request_id,
      steamId: user.steam_id,
    });

    return {
      success: true,
    };
  }
}
