export enum SystemSettingName {
  Updates = "updates",
  ChatMessageTtl = "chat_message_ttl",
  DemoNetworkLimiter = "demo_network_limiter",
  PublicDefaultModels = "public.default_models",
  SupportsDiscordBot = "public.supports_discord_bot",
  SupportsGameServerNodes = "supports_game_server_nodes",
  SupportsGameServerVersionPinning = "supports_game_server_version_pinning",
  NewsEnabled = "public.news_enabled",
  NewsLabel = "public.news_label",
  PostNewsRole = "public.post_news_role",
  RequireLoginForLiveStreams = "public.require_login_for_live_streams",
  ReleaseChannel = "release_channel",
  ReleaseChannelStatus = "release_channel_status",
}
