import { Job } from "bullmq";
import { WorkerHost } from "@nestjs/bullmq";
import { Logger } from "@nestjs/common";
import { UseQueue } from "../../utilities/QueueProcessors";
import { ScrimQueues } from "../enums/ScrimQueues";
import { PostgresService } from "../../postgres/postgres.service";
import { ScrimsService } from "../scrims.service";
import type {
  AvailabilityWindow,
  ScrimSettings,
  TeamRanks,
} from "../scrims.service";

type Candidate = ScrimSettings & {
  owner_steam_id: string | null;
  ranks: TeamRanks;
  availability: Array<AvailabilityWindow>;
};

const PROPOSE_OFFSET_MS = 15 * 60 * 1000;

@UseQueue("Scrims", ScrimQueues.ScrimMatcher)
export class MatchScrims extends WorkerHost {
  constructor(
    private readonly logger: Logger,
    private readonly postgres: PostgresService,
    private readonly scrims: ScrimsService,
  ) {
    super();
  }

  async process(_job: Job): Promise<void> {
    await this.scrims.expireStaleRequests();

    if (!(await this.scrims.isFinderEnabled())) {
      return;
    }

    await this.scrims.runScrimAlerts();
    await this.matchOpenPostings();
  }

  private async matchOpenPostings(): Promise<void> {
    const candidates = await this.loadCandidates();
    if (candidates.length < 2) {
      return;
    }

    const proposedAt = new Date(Date.now() + PROPOSE_OFFSET_MS);
    const blocked = await this.loadOpenPairs();

    for (let i = 0; i < candidates.length; i++) {
      for (let j = i + 1; j < candidates.length; j++) {
        const a = candidates[i];
        const b = candidates[j];

        if (blocked.has(this.pairKey(a.team_id, b.team_id))) {
          continue;
        }

        const regions = ScrimsService.regionsOverlap(a, b);
        if (regions.length === 0) {
          continue;
        }

        if (!ScrimsService.rangesOverlap(a, b, a.ranks, b.ranks)) {
          continue;
        }

        if (
          !ScrimsService.windowsOverlap(
            a.availability,
            b.availability,
            proposedAt,
            ScrimsService.matchDurationMinutes(1),
          )
        ) {
          continue;
        }

        if (!a.owner_steam_id) {
          continue;
        }

        try {
          await this.scrims.createScrimRequest({
            fromTeamId: a.team_id,
            toTeamId: b.team_id,
            requestedBySteamId: a.owner_steam_id,
            proposedScheduledAt: proposedAt,
            region: regions.at(0),
            autoGenerated: true,
          });

          blocked.add(this.pairKey(a.team_id, b.team_id));
        } catch (error) {
          this.logger.debug(
            `skipped auto scrim ${a.team_id} vs ${b.team_id}: ${
              error instanceof Error ? error.message : error
            }`,
          );
        }
      }
    }
  }

  private async loadCandidates(): Promise<Array<Candidate>> {
    const settings = await this.postgres.query<
      Array<
        ScrimSettings & {
          owner_steam_id: string | null;
          avg_elo: number | null;
          avg_faceit_level: number | null;
          avg_premier: number | null;
        }
      >
    >(
      `SELECT s.team_id, s.enabled, s.regions, s.elo_min, s.elo_max,
              t.owner_steam_id::text AS owner_steam_id,
              r.avg_elo, r.avg_faceit_level, r.avg_premier
         FROM team_scrim_settings s
         JOIN teams t ON t.id = s.team_id
         LEFT JOIN v_team_ranks r ON r.team_id = s.team_id
        WHERE s.enabled = true`,
    );

    if (settings.length === 0) {
      return [];
    }

    const teamIds = settings.map((row) => row.team_id);
    const availabilityRows = await this.postgres.query<
      Array<AvailabilityWindow & { team_id: string }>
    >(
      `SELECT team_id::text AS team_id, starts_at, ends_at, recurring_weekly
         FROM team_scrim_availability
        WHERE team_id = ANY($1::uuid[])`,
      [teamIds],
    );

    const availabilityByTeam = new Map<string, Array<AvailabilityWindow>>();
    for (const row of availabilityRows) {
      if (!availabilityByTeam.has(row.team_id)) {
        availabilityByTeam.set(row.team_id, []);
      }
      availabilityByTeam.get(row.team_id).push({
        starts_at: row.starts_at,
        ends_at: row.ends_at,
        recurring_weekly: row.recurring_weekly,
      });
    }

    return settings.map((row) => ({
      ...row,
      ranks: {
        avg_elo: row.avg_elo,
        avg_faceit_level: row.avg_faceit_level,
        avg_premier: row.avg_premier,
      },
      availability: availabilityByTeam.get(row.team_id) ?? [],
    }));
  }

  private async loadOpenPairs(): Promise<Set<string>> {
    const rows = await this.postgres.query<
      Array<{ from_team_id: string; to_team_id: string }>
    >(
      `SELECT from_team_id::text, to_team_id::text
         FROM team_scrim_requests
        WHERE status IN ('Pending', 'Countered', 'Matched')`,
    );

    const set = new Set<string>();
    for (const row of rows) {
      set.add(this.pairKey(row.from_team_id, row.to_team_id));
    }
    return set;
  }

  private pairKey(teamA: string, teamB: string): string {
    return [teamA, teamB].sort().join(":");
  }
}
