import { decodeShareCode } from "./shareCode";

describe("decodeShareCode", () => {
  // Vectors generated by canonically encoding a known
  // (matchId, outcomeId, tokenId) triple, so these assert the real Valve
  // byte layout rather than locking in whatever the decoder happens to emit.
  const vectors: Array<{
    code: string;
    matchId: bigint;
    outcomeId: bigint;
    tokenId: number;
  }> = [
    {
      code: "CSGO-fhdrj-2EkxQ-8Tqrn-bmDBE-3VeuA",
      matchId: 3299746880671809554n,
      outcomeId: 3299747158859251783n,
      tokenId: 38570,
    },
    {
      code: "CSGO-bB99d-EEBtm-RzCYc-GjD8g-ofYCA",
      matchId: 1n,
      outcomeId: 2n,
      tokenId: 3,
    },
    {
      code: "CSGO-dD8t8-YhkHS-JCvfT-Q5C2J-SnFDJ",
      matchId: 9344552100481608386n,
      outcomeId: 6212329227728025261n,
      tokenId: 49706,
    },
  ];

  it.each(vectors)("decodes $code", ({ code, matchId, outcomeId, tokenId }) => {
    expect(decodeShareCode(code)).toEqual({ matchId, outcomeId, tokenId });
  });

  it("is case-insensitive about the CSGO- prefix", () => {
    expect(decodeShareCode("csgo-bB99d-EEBtm-RzCYc-GjD8g-ofYCA")).toEqual({
      matchId: 1n,
      outcomeId: 2n,
      tokenId: 3,
    });
  });

  it("decodes the same code deterministically", () => {
    const code = vectors[0].code;
    expect(decodeShareCode(code)).toEqual(decodeShareCode(code));
  });

  it("throws on the wrong length", () => {
    expect(() => decodeShareCode("CSGO-ABC")).toThrow(/length/);
  });

  it("throws on characters outside the dictionary", () => {
    // '0' is intentionally absent from the share-code alphabet.
    expect(() => decodeShareCode("CSGO-00000-00000-00000-00000-00000")).toThrow(
      /character/,
    );
  });
});
