-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."match_lineup_players" add column "ready" boolean
--  not null default 'false';
