-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."match_options" add column "lan" boolean
--  not null default 'false';
