ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS discord_webhook text,
  ADD COLUMN IF NOT EXISTS discord_role_id text,
  ADD COLUMN IF NOT EXISTS "discord_notify_PickingPlayers" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Scheduled" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_WaitingForCheckIn" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_WaitingForServer" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Veto" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Live" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Finished" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Tie" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Canceled" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Forfeit" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_Surrendered" boolean,
  ADD COLUMN IF NOT EXISTS "discord_notify_MapPaused" boolean;
