table:
  name: settings
  schema: public
insert_permissions:
  - role: system_administrator
    permission:
      check: {}
      columns:
        - name
        - value
    comment: ""
select_permissions:
  - role: system_administrator
    permission:
      columns:
        - name
        - value
      filter: {}
    comment: ""
  - role: user
    permission:
      columns:
        - name
        - value
      filter:
        name:
          _like: public.%
    comment: ""
update_permissions:
  - role: system_administrator
    permission:
      columns:
        - name
        - value
      filter: {}
      check: {}
    comment: ""
delete_permissions:
  - role: system_administrator
    permission:
      filter: {}
    comment: ""
