-- Allow a player to hold both a placement trophy (gold/silver/bronze) and MVP
-- on the same tournament. The old uniqueness key blocked the second insert
-- when the MVP was on the winning team.
--
-- Idempotent: the previous constraint's name is auto-generated by Postgres
-- (inline UNIQUE in the original migration), and truncation varies by
-- version / NAMEDATALEN, so look it up by column set. Also guard the new
-- constraint so re-running is safe.
DO $$
DECLARE
    v_conname text;
BEGIN
    SELECT c.conname
    INTO v_conname
    FROM pg_constraint c
    WHERE c.conrelid = 'public.tournament_trophies'::regclass
      AND c.contype = 'u'
      AND (
          SELECT array_agg(a.attname::text ORDER BY a.attname::text)
          FROM unnest(c.conkey) AS k(attnum)
          JOIN pg_attribute a
            ON a.attrelid = c.conrelid AND a.attnum = k.attnum
      ) = ARRAY['player_steam_id', 'tournament_id', 'tournament_team_id']::text[];

    IF v_conname IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.tournament_trophies DROP CONSTRAINT ' || quote_ident(v_conname);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.tournament_trophies'::regclass
          AND conname = 'tournament_trophies_tournament_team_player_placement_key'
    ) THEN
        ALTER TABLE public.tournament_trophies
            ADD CONSTRAINT tournament_trophies_tournament_team_player_placement_key
            UNIQUE (tournament_id, tournament_team_id, player_steam_id, placement);
    END IF;
END $$;
