-- Allow a player to hold both a placement trophy (gold/silver/bronze) and MVP
-- on the same tournament. The old uniqueness key blocked the second insert
-- when the MVP was on the winning team.
--
-- The previous constraint was created via an inline UNIQUE (...) in the
-- original migration, so its name is auto-generated by Postgres. The exact
-- truncation of that name varies across Postgres versions / NAMEDATALEN, so
-- look it up by column set instead of relying on the expected name.
DO $$
DECLARE
    v_conname text;
BEGIN
    SELECT c.conname
    INTO v_conname
    FROM pg_constraint c
    WHERE c.conrelid = 'public.tournament_trophies'::regclass
      AND c.contype = 'u'
      AND (
          SELECT array_agg(a.attname::text ORDER BY a.attname::text)
          FROM unnest(c.conkey) AS k(attnum)
          JOIN pg_attribute a
            ON a.attrelid = c.conrelid AND a.attnum = k.attnum
      ) = ARRAY['player_steam_id', 'tournament_id', 'tournament_team_id']::text[];

    IF v_conname IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.tournament_trophies DROP CONSTRAINT ' || quote_ident(v_conname);
    END IF;
END $$;

ALTER TABLE public.tournament_trophies
    ADD CONSTRAINT tournament_trophies_tournament_team_player_placement_key
    UNIQUE (tournament_id, tournament_team_id, player_steam_id, placement);
