-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."player_kills" add column "in_air" boolean
--  not null default 'false';
